# This file is meant to be our API testing environments as it allows us to send requests from here
# INSTEAD OF WRITING YOUR DOCUMENTATIONS ON HOW TO CALL A PARTICULAR API ENDPOINT OR PARAMS,
# PLEASE USE THIS FILE TO UPDATE THEM
# Note: You must install this extension from your VS Code Extensions Market place (apirest)

############################# BELOW IS AN EXAMPLE ON HOW IT WORKS AND USE CASE ################################

### ========= CUR_SESSION API ==================

### GET CUR_SESSION
# http://localhost/schola/api/cur_sessionapi/get_cursession.php
# https://beta-schola.myf2.net/api/cur_sessionapi/get_cursession.php


# ### ========= SUBJECT API ==================
# ### GET A SUBJECT
# httpS://maclesleyinternationalschools.com.ng/api/subjectapi/getsubject.php?subject_id=2

# ### GET A SUBJECT
# http://localhost/schola/api/subjectapi/getsubject.php?subject_id=2


# ### GET ALL SUBJECTS
# http://localhost/schola/api/subjectapi/getsubjects.php


# ### CRAETE A SUBJECT
# POST http://localhost/schola/api/subjectapi/createsubject.php

# {
#     "subject_name": "AMALA SC",
#     "subject_code": "ASmat",
#     "staff_id": 1
# }

# ### UPDETE A SUBJECT
# POST http://localhost/schola/api/subjectapi/updatesubject.php

# {
#     "subject_id": "1",
#     "subject_name": "Mathematics",
#     "subject_code": "mat",
#     "staff_id": 1
# }

### ========SUBJECT API ENDS HERE ========

############################## PATIENT API EXAMPLES 

###### GET MEDICAL HISTORY WITH PATIENT ID = 1
GET localhost/Capital_Health(original)/Capital_Heath_org/api/patient/?request=get_medical_history&pId=1

### REGISTER A PATIENT
POST localhost/Capital_Health(original)/Capital_Heath_org/api/patient/?request=register
{
    "firstname": "John",
    "lastname": "Doe",
    "email": "john.doe@example.com",
    "password": "securepassword",
    "confirm_password": "securepassword",
    "gender": "Male",
    "date_of_birth": "1990-01-01",
    "phone": "1234567890",
}

### PATIENT LOGIN
POST localhost/Capital_Health(original)/Capital_Heath_org/api/patient/?request=login
{
    "email": "jamesdoe@example.com",
    "password": "12345"
}

### GET PATIENT DETAILS WITH PATIENT ID = 1
GET localhost/Capital_Health(original)/Capital_Heath_org/api/patient/?request=get_profile&pId=1

### ADD MEDICAL HISTORY FOR PATIENT ID = 1
POST localhost/Capital_Health(original)/Capital_Heath_org/api/patient/?request=add_medical_history&pId=1
{
    "patient_id" : "2",
    "allergies" : "Pepper",
    "current_medications" : "none",
    "past_illnesses" : "none",
    "surgeries" : "['yes', 'hyiner']",
    "family_history" : "High BP",
    "current_conditions" : "Healthy",
    "genotype" : "AA",
    "blood_group" : "O",
    "blood_pressure" : "120/80",
    "blood_sugar" : "50%"
}

### GET PATIENT MEDICAL HISTORY
GET localhost/Capital_Health(original)/Capital_Heath_org/api/patient/?request=get_medical_history&pId=2